{% set name = "khiops" %}
{% set version = "11.0.0.0b.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/khiops-{{ version.replace("b.0", "b0") }}.tar.gz
  sha256: ec6ffb3eda2eb2168737de4b5b90c0f04f93ddad405742e052271193d706ffd1

build:
  entry_points:
    - kh-status=khiops.tools:kh_status_entry_point
    - kh-samples=khiops.tools:kh_samples_entry_point
    - kh-download-datasets=khiops.tools:kh_download_datasets_entry_point
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - khiops-core =11.0.0b.0
    - pandas >=0.25.3
    - scikit-learn >=0.22.2
  run_constrained:
    # do not necessary use the latest version
    # to avoid undesired breaking changes
    - boto3 >=1.17.39,<=1.35.69
    - google-cloud-storage >=1.37.0

test:
  imports:
    - khiops
  commands:
    - pip check
    - kh-status
    - kh-samples --help
    - kh-download-datasets --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://khiops.org/11.0.0-b.0/
  summary: Python library for the Khiops AutoML suite
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://khiops.org/11.0.0-b.0/api-docs/python-api
  dev_url: https://github.com/khiopsml/khiops-python

extra:
  recipe-maintainers:
    - popescu-v
    - tramora
