{% set name = "khiops" %}
{% set version = "10.3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/khiops-{{ version }}.tar.gz
  sha256: 6daa4d4bc733c5d68e49ba217dc3ce888582ffed14a79e60741a22c73461fbb6

build:
  entry_points:
    - kh-status=khiops.tools:kh_status_entry_point
    - kh-samples=khiops.tools:kh_samples_entry_point
    - kh-download-datasets=khiops.tools:kh_download_datasets_entry_point
    - pk-status=khiops.tools:pk_status_entry_point
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - khiops-core =10.3.2
    - pandas >=0.25.3
    - scikit-learn >=0.22.2
  run_constrained:
    # do not necessary use the latest version
    # to avoid undesired breaking changes
    - boto3 >=1.17.39,<=1.35.69
    - google-cloud-storage >=1.37.0

test:
  imports:
    - khiops
  commands:
    - pip check
    - kh-status
    - kh-samples --help
    - kh-download-datasets --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://khiops.org
  summary: Python library for the Khiops AutoML suite
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://khiops.org/api-docs/python-api
  dev_url: https://github.com/khiopsml/khiops-python

extra:
  recipe-maintainers:
    - popescu-v
    - tramora
